#!/bin/bash
#
	echo ""
	echo "Assembling DSP code for a CCD"
	echo ""
#
# DOWNLOAD selects application code to be loaded from EEPROM or 
#   downloaded from the host over the fiber optic link
#
# DOWNLOAD = HOST or ROM



DOWNLOAD="HOST"
WAVEFORM_FILE="$1.waveforms"
DST_FILE="firmware_$1_simple"
#DST_FILE=$1


wine ./motorolaCompiler/ASM56300 -b -ltim.ls -d DOWNLOAD $DOWNLOAD -d WAVEFORM_FILE "$WAVEFORM_FILE" tim_simple.asm
wine ./motorolaCompiler/DSPLNK -btim.cld -v tim_simple.cln 
rm -f "$DST_FILE".lod
wine ./motorolaCompiler/CLDLOD tim.cld > "$DST_FILE".lod
rm -f tim.cln ; rm -f tim.cld
#dos2unix "$DST_FILE".lod

if [ "$DOWNLOAD" = "HOST" ] ; then
	echo ""
	echo "Created file $DST_FILE.lod for downloading over optical fiber"
	echo ""
fi


